kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: backup-test
nodes:
- role: control-plane
  image: kindest/node:v1.28.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30432
    hostPort: 5432
    protocol: TCP
