apiVersion: batch/v1
kind: CronJob
metadata:
  name: rds-backup-job-local
  namespace: default
spec:
  schedule: "*/5 * * * *"   # every 5 minutes for testing
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rds-backup
              image: postgres:15
              command:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  
                  # Install AWS CLI via pip to avoid ELF/rosetta incompatibilities
                  apt-get update && apt-get install -y python3-pip
                  pip3 install --no-cache-dir awscli
                  
                  # Set up environment for LocalStack
                  export PGPASSWORD=$(cat /secrets/db-password)
                  export AWS_ACCESS_KEY_ID=$(cat /aws-secrets/aws-access-key-id)
                  export AWS_SECRET_ACCESS_KEY=$(cat /aws-secrets/aws-secret-access-key)
                  export AWS_DEFAULT_REGION=us-east-1
                  export AWS_ENDPOINT_URL=http://host.docker.internal:4566
                  
                  TIMESTAMP=$(date +%F-%H-%M-%S)
                  
                  echo "🚀 Starting LOCAL backup test at $(date)"
                  echo "📊 Target: ${RDS_REPLICA_HOST}"
                  echo "📦 LocalStack S3: s3://rds-db-backups-co-create"
                  
                  # Test database connection
                  pg_isready -h $RDS_REPLICA_HOST -p 5432 -U root
                  
                  if [ $? -ne 0 ]; then
                    echo "❌ Cannot connect to database"
                    exit 1
                  fi
                  
                  echo "✅ Database connection verified"
                  
                  # Stream to file first to avoid AWS CLI "x-amz-trailer" issue in LocalStack
                  echo "🔄 Creating dump file..."
                  TMP_DIR=/tmp/rds-backups
                  mkdir -p "$TMP_DIR"
                  DUMP_FILE="$TMP_DIR/langfuse_backup.dump"

                  pg_dump -h $RDS_REPLICA_HOST -U root -p 5432 \
                    --format=custom \
                    --blobs \
                    --verbose \
                    --no-password \
                    langfuse \
                    -f "$DUMP_FILE"

                  echo "☁️ Uploading dump via s3api put-object..."
                  aws s3api put-object \
                    --bucket rds-db-backups-co-create \
                    --key $TIMESTAMP/langfuse_backup.dump \
                    --body "$DUMP_FILE" \
                    --endpoint-url http://host.docker.internal:4566

                  echo "✅ Successfully backed up to LocalStack S3!"
                  # Verify upload in LocalStack
                  aws s3 ls s3://rds-db-backups-co-create/$TIMESTAMP/ \
                    --endpoint-url http://host.docker.internal:4566 \
                    --human-readable
                  
                  echo "🎉 LOCAL backup test completed at $(date)"
                  unset PGPASSWORD
              env:
                - name: RDS_REPLICA_HOST
                  value: "postgres-replica-service.default.svc.cluster.local"
              volumeMounts:
                - name: db-secrets
                  mountPath: /secrets
                  readOnly: true
                - name: aws-secrets
                  mountPath: /aws-secrets
                  readOnly: true
          volumes:
            - name: db-secrets
              secret:
                secretName: rds-db-root-secret
            - name: aws-secrets
              secret:
                secretName: aws-credentials